version: '3.8'

services:
  go-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.go
    environment:
      # Cambia el host en DB_CONN_STR a localhost
      DB_CONN_STR: postgresql://postgres:root@localhost:5432/mydb
    ports:
      - "8080:8080"

  python-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    environment:
      # Cambia el host en DB_CONN_STR a localhost
      DB_CONN_STR: postgresql://postgres:root@localhost:5432/mydb
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
