version: '3.8'

services:
  go-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.go
    environment:
      - PORT=8080
      - DB_CONN_STR=postgresql://user:password@postgres:5432/mydb
    ports:
      - "8080:8080"

  python-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    environment:
      - PORT=5000
      - DB_CONN_STR=postgresql://user:password@postgres:5432/mydb
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
